language: bash
services: docker
env:
  secure: ze2FTRga9GfaCjgbWqMDt0d+ni8JRMvyV2BXtUiocMxgmdpULhOt5grjgtyVKSdPwz7ZIh28zdDu4mooKrDlG5wjRuuAMR1Cp1UYm8cIjgyIMwGdzQWIH1G99h0/w9UUdTTahNVAZNxeFkov8zIXKhaTDuG7qhsW9Deu7hrUCyk6aRWJJo2c6hvSusMi4IYvOP5wZunEvmC6fzxxM9bQhtflke9GL0qVB7w0E4i/5gQKbnzGzeoZ6az1B0rSNnAhXoyd4AcodMoI77zXZ/ZLSijuGfpeUu4/RyMBBVKLmaD57pQADiL4EnPy0cv8iw9o3+iEjEiQr1us5nFIECL+Ok4pgeyk0O+nXzmrsTXQJcgvGoCB99fB5YRVNB5sx+6UIfi/CPLb0NAsDuioU/J6FkkYftc2RMPFcj4cUs/3Zo1UhIKZWPMsZl2eHKulgTYp0MCG9CmyzGTljebciutThGrmEGtEMqPDK+qDeb2XJ5grxAcYCWRfKi5KFYyiEEdl/kF7Qw+fLyBMvM8X02cbJBrELwArjN1cCHkQSANHYwi7i+ZwIAfOonqG1I5JSG8XclcG//XH6y4buSAbaGDxfX3NEdwYcNv5D63mh9H9ywOVP0mnxFhzacvgzg3tCgYqqdgsG860/fPsvD+dwQGuwYvTomNoZw3Kb8r2ATc53Jk=
addons:
  apt:
    packages:
    - realpath
before_install:
- if [ -n "$TRAVIS_TAG" ]; then export TAG=$TRAVIS_TAG; else export TAG=ci; fi
- export TAG=$(echo $TAG | sed 's;/;_;g')
- env | sort | egrep "REPO|TAG|REGISTRY" | egrep -vi "password|token"
- bin/build
- docker images
script: true
after_success: if [ -n "$TRAVIS_TAG" ]; then bin/push; fi
notifications:
  slack:
    secure: 2o4Wxc2DKldZ+KDQ5rhkuCEAclKqxuubnV1HS810ZE9BrC0WBatMQX0bcQpU3shsslTdgPontMVmdi6LbrYjp1jgq64wPypXOWxNMC8+xm2gZKxvIP6GLcJx25r6Oj1ok6QTVO/ZuTNRXYe2e60rwnFgjM8/TPtMNDBESpaX+tZfsu098iwR3GLWkZVKMPZa91tXIJXl4qfkOPjye5rrdOsVL8uBvlgfS52g5Jt91xTCJtEOFC2jPLFG9oS5m+q7mc8t2f3QI4VXJCZfoCk+ChcvwaXeHgk8a8LX6o9e27QMpbBzqW8iPiAQTxXxUiYmYwbV+XWTERJEa9bjufZ/8/4jGXAKHDWgFK1bKvw/+/fLltK+rxR/xmwnhZj1A5kkplpeNwR1NPFRe5zyUDyJ1Eis72UdPIZZXvO6mdEvMp2R8rb1xObKX9z3vPQNGWceCs5VBz9g3OkCZDzWpRsDpRds0ooKwt/UUtYLGPRf/DlrsfcJgnLJZ6NDri8ZGn0RIhaqi+vwSY0YjlGYoWKraOyJvt013VqVWU+AKLtPrpNa0glTrqx/vk/9MgFF3f9L9dPv5iLKAZvIgkFjFSG4R5k6H5/pZW4oUu95mWnTV+c+S+55pH6+boBL48fRaJo6hNZk4IaJ2hHeTBiYlejGGgzphSD0YW1p1nK0r1hcSig=
