language: bash
services: docker
env:
  secure: FUab7+Hp6ev10T7m/zq9MN9B0ReGOdNSE7xrgx9YsA4zDsIwezEnoo1uh1M4RQGnV0OAvclNdNdv5ggGV91ij64ETpKTX6NUev9MO8zdOWw0wMrSi9/AOP0lbKH/M52IQs60zD+fJ9StHqt7DP6krfIjHa0/0YmhZKynQn7dNwI4rriZVOUuveYvVOATA7HGdDDHLqlUN6sUEjLlUpe2WkqmB1EDwgioVGe59slvlIZ9nUKHlRHFIacA2W93RO/o4DuHjjbYJZy1Lw7aWZ3yF3VO3S6tHvuw1Q1daT2mBrnNl3K+SMAJI1BqtfEXtA9Zu8t8Hb42XbGWzvsPwU1nP46InK6+wz15/A49KOFtGwMfVfg5uPon565sQ3vPqxSJ/QxHtGB2GsgfmTlxbuOgY6hKNwh1qWMlWiIaCFFf6++rnDT4ZLVMg3t9mp4tQDqMxASRAiX5X4CFte3oOjeOWAHIxbHa39cQ7wAWpmEptU4RJlyuXhjJp0W4NjuD9KqmgxizYJO8uCUkOfHBGH2BpicqxF6hWnGe0/fJm/JSuQjsGs1SPgcQIvHanrbeAEIIrrkQSnxClxsFxXWLxWTiRei3N/q5wb9/Ew4GfhUV49i8YzgE+wa/AIYO/PWGIaQWjF4sYo59CJaiM7ES/e2NdPcxL+1QDEMuVNsHT7X0/pM=
addons:
  apt:
    packages:
    - realpath
before_install:
- if [ -n "$TRAVIS_TAG" ]; then export TAG=$TRAVIS_TAG; else export TAG=ci; fi
- export TAG=$(echo $TAG | sed 's;/;_;g')
- env | sort | egrep "REPO|TAG|REGISTRY" | egrep -vi "password|token"
- bin/build
- docker images
script: true
after_success: if [ -n "$TRAVIS_TAG" ]; then bin/push; fi
notifications:
  slack:
    secure: 2o4Wxc2DKldZ+KDQ5rhkuCEAclKqxuubnV1HS810ZE9BrC0WBatMQX0bcQpU3shsslTdgPontMVmdi6LbrYjp1jgq64wPypXOWxNMC8+xm2gZKxvIP6GLcJx25r6Oj1ok6QTVO/ZuTNRXYe2e60rwnFgjM8/TPtMNDBESpaX+tZfsu098iwR3GLWkZVKMPZa91tXIJXl4qfkOPjye5rrdOsVL8uBvlgfS52g5Jt91xTCJtEOFC2jPLFG9oS5m+q7mc8t2f3QI4VXJCZfoCk+ChcvwaXeHgk8a8LX6o9e27QMpbBzqW8iPiAQTxXxUiYmYwbV+XWTERJEa9bjufZ/8/4jGXAKHDWgFK1bKvw/+/fLltK+rxR/xmwnhZj1A5kkplpeNwR1NPFRe5zyUDyJ1Eis72UdPIZZXvO6mdEvMp2R8rb1xObKX9z3vPQNGWceCs5VBz9g3OkCZDzWpRsDpRds0ooKwt/UUtYLGPRf/DlrsfcJgnLJZ6NDri8ZGn0RIhaqi+vwSY0YjlGYoWKraOyJvt013VqVWU+AKLtPrpNa0glTrqx/vk/9MgFF3f9L9dPv5iLKAZvIgkFjFSG4R5k6H5/pZW4oUu95mWnTV+c+S+55pH6+boBL48fRaJo6hNZk4IaJ2hHeTBiYlejGGgzphSD0YW1p1nK0r1hcSig=
