language: bash
services: docker

env:
  - |
    BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} # Branch name
    PR_SHA=${TRAVIS_PULL_REQUEST_SHA::8}                 #
    COMMIT_SHA=${TRAVIS_COMMIT::8}                       #
    COMMIT=${PR_SHA:-$COMMIT_SHA}                        # Commit hash (XXXXXXXX)
    BUILD=$(printf "%04d\n" $TRAVIS_BUILD_NUMBER)        # Build number (0000)
    TAG=$BRANCH-$COMMIT-$BUILD                           # Docker tag (branch-XXXXXXXX-0000)
    RELEASE=$TRAVIS_TAG                                  # New release indicated by Git tag (X.Y.Z)
    REPO=${REGISTRY_HOST:-docker.io}/bigdatauniversity/course-dev.chell

before_install:
  - if [ -n "$RELEASE" ]; then export TAG=$RELEASE; fi
  # Ensure TAG doesn't have any slashes (`/`)
  - export TAG=$(echo $TAG | sed 's;/;_;g')
  - env | sort | egrep "REPO|TAG|REGISTRY" | egrep -vi "password|token"
  - docker-compose -f ci/docker-compose.yaml build
  - docker images

script:
  - docker-compose -f ci/docker-compose.yaml run --rm chell ./ci.sh

after_success:
  - if [ -n "$RELEASE" ]; then ci/push.sh; fi

notifications:
  slack:
    secure: "SG0hq8WsgaMiFyxLgcLQpROkedsoeIkT8Psr8WwUc0sz4K+8zkXgw9uI2ffvadPmCodI7aTF2lymHYZaOVoq1yuHOzE5sYdawtdebCjYmFrFQ6l5MnISX10nJFmUqjsaARHGrImsEouuLltW9V55fvCgV+8Eab/MbvcJBOrVgqhIIi94ykeV9a9fKMTpnGGF8weXZNpAgfUNdvDfsMRsfdiDgMaBKQFT6Xe0XUTV6nKaqiVkVVI4WSayneoGgAzZBCVBoVLRJ/B7ghHHQLga+K9lUFkX6yQDY6OS9Dv6UaNA7RxC3tyVX9z5NTEUL5Q5AdxEctDdvwoz8ugo8pqHtaovtJI1T7124K/rEjZMVBX+TKudS+9GyAlv0/1hR2bLH5SOENvnKhMzHrsAxyGCqPzwbT8srj23He8EtSCJ3H8PkpRxhBKItNvRvtFy/MnUZeXh9DDr/OVLpsHCgPL8g4WfqLp9pFlwVRkMcJlHRX7OTntFL+2GQVP9n1NbrmH5Psg6xgbSJcZnZ5ThBzKdqXdz2NsbFETD8GhuUxnmD3hFU9GaxHBpRuEm/6hRbazU3uktw9vpptjOsFpOGbeSEnjZUEFy5uRuwWflsrfkzCzI1GhNiuYXc3l7Yme99s//Z/hNiW1jJsqlnygIxKW+GcSI2/+PvS7Ox4PDIbvZU5A="
