language: bash
services: docker
env:
  secure: wm4UpPpmPgBaIkF1KLlk0PRdg9Zoah+PBXiA6WUpA1Gyaz8HXqe2aRVvE6RcJ11l/SNcTtNtwY/UP6zBiblwJn6819WdfGqA87oFRZZddWyuzCxFE0YL1xV5EevSqRzRKlGFqlUiHkX4XaxNw51W7BFaKrOPQqG0DP+QCNzgOS+Ydt1V5nDZ+utH2Q+V/Rn3OtD9dsr5z3EzjSSg4W5YIq2bCWV8cSXHAar1cGosevWjvGo6tDCUL+RYOzJFlGvIJuRjjbVIlpJGZURC7kLmDXjO5R4UUH7eATlQEN/eN8D2tg+yZOUfa6gHaTOTyNvjOHLmBW/W1vlG8xsg5Iy2V5IL7ET+ESkPrn9gh/VaxUglFP5Xh8T5YFBc8lJ7g0CWFaAjgrfjUyjTMn6HMo45MdKEp15Cc++k3Dyt+d5JG5HzI06dzqLE+WvfDAz/4zsgRdbBpvRBVccSPDGEo5fnzO7un4GkP0GkDUER3lvHEdZwBvcaTykuDqS9SFgHWY7FeEUcgJSpy1Ahw6CMLVo4LITN+zJYY7Neh12YaudCCJnrjY1b/iGjcGatvtUKcVedomDgffnq9yi7HKNoKVrxhCNxzHjRLHh99h2aZ9nGitTmbRQW6QnxhSV+cTO7zZn7IZiKVO/6K39KR9ebL+/j6ldNz89F+bCVE9YpQOb/om4=
addons:
  apt:
    packages:
    - realpath
before_install:
- if [ -n "$TRAVIS_TAG" ]; then export TAG=$TRAVIS_TAG; fi
- export TAG=$(echo $TAG | sed 's;/;_;g')
- env | sort | egrep "REPO|TAG|REGISTRY" | egrep -vi "password|token"
- bin/build
- docker images
script: true
after_success: if [ -n "$TRAVIS_TAG" ]; then bin/push; fi
notifications:
  slack:
    secure: hK0xiNDqHLXhugFvAJMjKaO16pFmGfYoin6126ewEc5tquWHARkKALIilLv9kHlolCvxV9XYvfU7a67UqYFmkehrWKSvzwoTu+Kvc4xa14ODYrhqXIgrFs1ZmdK1CcCG2LtPMDUmdde67YoXWH1V44jlqrrOa73qhawOKa+pUJXh+fOPquHXMCVpnJtUD1QBEidnMkrVbmpYnwSY9n99pL7oRE1uDx8vaLLE2EW3KL8pwSJZveGDKIpbxpnGhlNGY18cZEbUm86oJ2z5AiEVqrWqUx1WnaQUPrER2aQpNSgXCf1OUIj8Fg6SnimEA7h3Pv0t1OgHWvn906X3Q4QUGeuaKvjF+Vqhbb6A6cduMT6cbB9yeioDKSpIzPOW5fcELFHWLXfsN3DJjYRClYlGOnmyVGq1M87Q0RFl6N09Cl9Z2omWpTrsfMkFTacFiu+sPJK6UKVjJ7M1tHv0cTNTiMCkw62T+/nTJfrZdlC+cVjUzNUr1jb9pT7K3eX1m/PiQKjAW+yTedQKTa7x4Xz3yuXEF6r42aubmNLX1JDtqnEIHvRNdMC0UxkhyQLe0HO2jSHaljyML0acz/ihU77u8HTpFWlVDZ/44be81Zf53iNEd25NovLLaSa9yXN5FgewtOxYfYQZQ9A44SQhWNXSi+W7L9lkr/1cz320wyMR/ZQ=
