language: bash
services: docker
env:
  secure: '09SaplMYjic0hl8paSF/OQO6CS1AA8alhaePsJsS0uIA3Lp8CMoXd6enZFtjrKzHNhue4xZhEkCtpVyvS4Hnfd4oimti18ZWEMgrMrHWnJmv+dDXWj5ElsNsQ8mSlZ3Aw090J5Rfy+zSuokL0gAtaYG1CJw2++BE1lvN4wJjXaOz0X+I+5sSWIjjHPYoGHwSJ1LrCgMK877siLQs1931quZLjx3D1iqy0/BRN5Luca4tCBpKaon34YzYBBDzhwlWtCryfyVbZjKGmucD0eT7NtH8Z3UuB1esHijVxnSWg9YuaB0Ntsqwrk1hSNARznaG/WLtUDV/Ov7BZPCv7ezWABqyEna8pHc139xLTytW4bXX3UT3imOZYjhk5+Anm8Pg88dis7O+YjbJ0jR8ROQRyqOVs6DV4x7cJHngToQsTdIvAL4Ukuq10Km4r5u/DYmBIlG7F8YePhJ3wkW2NF0J0wTarJXh6/VoOi8f6B/6g4rOOX+3xq8WGxdxW4yiOK6zknpBVY7tVG+f9NWDblOKRF9pj+Ruga9pDkRCooTqvXyUff4/Q3xW697QeHTwE9WlBJ9JQ9pzJdY7fDEsUT0MKwDcy0rMZL8GaFHLV+KqYv9nrgxElv/BRm6rqXRqny/AlwIEDh7TQnrJec23Q9FCcnW5CjOxFgL+1vqKM1mi+CM='
addons:
  apt:
    packages:
    - realpath
before_install:
- if [ -n "$TRAVIS_TAG" ]; then export TAG=$TRAVIS_TAG; fi
- export TAG=$(echo $TAG | sed 's;/;_;g')
- env | sort | egrep "REPO|TAG|REGISTRY" | egrep -vi "password|token"
- bin/build
- docker images
script: true
after_success: if [ -n "$TRAVIS_TAG" ]; then bin/push; fi
notifications:
  slack:
    secure: 2o4Wxc2DKldZ+KDQ5rhkuCEAclKqxuubnV1HS810ZE9BrC0WBatMQX0bcQpU3shsslTdgPontMVmdi6LbrYjp1jgq64wPypXOWxNMC8+xm2gZKxvIP6GLcJx25r6Oj1ok6QTVO/ZuTNRXYe2e60rwnFgjM8/TPtMNDBESpaX+tZfsu098iwR3GLWkZVKMPZa91tXIJXl4qfkOPjye5rrdOsVL8uBvlgfS52g5Jt91xTCJtEOFC2jPLFG9oS5m+q7mc8t2f3QI4VXJCZfoCk+ChcvwaXeHgk8a8LX6o9e27QMpbBzqW8iPiAQTxXxUiYmYwbV+XWTERJEa9bjufZ/8/4jGXAKHDWgFK1bKvw/+/fLltK+rxR/xmwnhZj1A5kkplpeNwR1NPFRe5zyUDyJ1Eis72UdPIZZXvO6mdEvMp2R8rb1xObKX9z3vPQNGWceCs5VBz9g3OkCZDzWpRsDpRds0ooKwt/UUtYLGPRf/DlrsfcJgnLJZ6NDri8ZGn0RIhaqi+vwSY0YjlGYoWKraOyJvt013VqVWU+AKLtPrpNa0glTrqx/vk/9MgFF3f9L9dPv5iLKAZvIgkFjFSG4R5k6H5/pZW4oUu95mWnTV+c+S+55pH6+boBL48fRaJo6hNZk4IaJ2hHeTBiYlejGGgzphSD0YW1p1nK0r1hcSig=
