language: bash
services: docker

env:
  - |
    BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} # Branch name
    PR_SHA=${TRAVIS_PULL_REQUEST_SHA::8}                 #
    COMMIT_SHA=${TRAVIS_COMMIT::8}                       #
    COMMIT=${PR_SHA:-$COMMIT_SHA}                        # Commit hash (XXXXXXXX)
    BUILD=$(printf "%04d\n" $TRAVIS_BUILD_NUMBER)        # Build number (0000)
    TAG=$BRANCH-$COMMIT-$BUILD                           # Docker tag (branch-XXXXXXXX-0000)
    RELEASE=$TRAVIS_TAG                                  # New release indicated by Git tag (X.Y.Z)
    REPO=${REGISTRY_HOST:-docker.io}/bigdatauniversity/course-dev.chell

before_install:
  - if [ -n "$RELEASE" ]; then export TAG=$RELEASE; fi
  # Ensure TAG doesn't have any slashes (`/`)
  - export TAG=$(echo $TAG | sed 's;/;_;g')
  - env | sort | egrep "REPO|TAG|REGISTRY" | egrep -vi "password|token"
  - docker-compose -f ci/docker-compose.yaml build
  - docker images

script:
  - docker-compose -f ci/docker-compose.yaml run --rm chell ./ci.sh

after_success:
  - if [ -n "$RELEASE" ]; then ci/push.sh; fi

notifications:
  slack:
    secure: "YXroLSEtHrgB/PWcVzEN5+2uWLKRjPrDftPOwhq44D7i7ZrTpvTUSfZgjvXzJ/wZI7ADy4AQCHNTLtK3Dm44DHeFKDN/v06jdipu5GDXZCw45IdmQht1yQjjV998F5dJoJeGjKUDc0Sc6NX0l/1TFV1M8mh5uE5815j5vkfK3epxLaOodEkbr3d6B9G+Y9pIddvE2BqYwAObjWEhuNQlkpJ6laqwZZW8wZet3rl9dji8L1qw8dLvTMVqbjL38eOr8MnFK7dM7u1WgR41rD30lTrf+uiXWfVcLp4SKVUSEbcNuHooiEAW6Jxm9egV5BJr6rQxJNkbhAbTSbVr8TxrAEsfQVQpk41t8PDaAhzkKe8F6u7HohojPW9DMPXREdlmobm9acES11i0D7nFpYc6+1nBgCjh24i5UJ+PcZ6u49dy0sqSaJGigI1iFAQVNgDAprLEXvyIK86jls7KUmX7vy3W6kLS+80ij1iYf9gM5TSJoN4y5wS5XolVsMAQDmsfp1pv9eGE1UiEA+dLwr1f1MEjLoESE02eTlu9Qxiz0tEgbp4aZVQo+jaSyouvvhpwrHcOQeti0ruzAaIc4Hr7+ddyrr/dAxLNiFaFPoaJ2JkoeMd1M2lNJ7cOy0Ec0QX/sw1giI4XLKaTdKutReUcFHBFiMMfqqCPP3QC+nNSk3g="
