version: '2'
volumes:
  mongo-data:
services:
  chell:
    image: apset-docker.artifactory.swg-devops.com/bigdatauniversity/course-dev.chell
    ports:
      - "3000:3000"
    environment:
      - DEBUG=chell:*
      - COOKIE_SECRET

      - CHELL_ACCESS_KEY
      - CHELL_SECRET_KEY

      - COURSE_DEV_LMS_URL
      - COURSE_DEV_CLIENT_ID
      - COURSE_DEV_CLIENT_SECRET
      - COURSE_DEV_CALLBACK_URL

      - COMPANION_CUBE_URL
      - COMPANION_CUBE_ACCESS_KEY
      - COMPANION_CUBE_SECRET_KEY

      - MONGO_URI=mongodb://mongo/chell
    links:
      - mongo
    volumes:
      - ./chell:/srv/chell

  mongo:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
