version: '2'
volumes:
  mongo-data:
services:
  chell:
    image: apset-docker.artifactory.swg-devops.com/bigdatauniversity/course-dev.chell
    ports:
      - "3000:3000"
    environment:
      - DEBUG=chell:*
      - COOKIE_SECRET

      - SKIP_LOGIN

      - CHELL_ACCESS_KEY
      - CHELL_SECRET_KEY

      - MESA_LMS_URL
      - MESA_OAUTH2_CLIENT_ID
      - MESA_OAUTH2_CLIENT_SECRET
      - MESA_OAUTH2_CALLBACK_URL

      - COMPANION_CUBE_URL
      - COMPANION_CUBE_ACCESS_KEY
      - COMPANION_CUBE_SECRET_KEY

      - MONGO_URI=mongodb://mongo/chell

      - S3_ENDPOINT
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET
    links:
      - mongo
    volumes:
      - ./chell:/srv/chell

  mongo:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db
