version: "2"

services:
  #
  # GlaDOS
  #
  glados:
    build: ./gamora
    image: bigdatauniversity/portal.gamora
    environment:
      # development purposes only
      - PIP_REPO_HOST_WITH_CREDS
      - PIP_REPO_USERNAME
      - PIP_REPO_PASSWORD
