version: "2"

services:
  #
  # Gamora
  #
  gamora:
    build:
      context: ./gamora
      args:
        - PIP_REPO_HOST_WITH_CREDS
        - PIP_REPO_USERNAME
        - PIP_REPO_PASSWORD
    image: bigdatauniversity/portal.gamora:$TAG
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER
      - MYSQL_PASSWORD

      - MONGO_BACKUP_USER
      - MONGO_BACKUP_PASSWORD
      - MONGO_HOST=mongo
      - SENTRY_DSN
      - SOFTLAYER_USER
      - SOFTLAYER_API_KEY
      - SOFTLAYER_DATACENTER
      - SOFTLAYER_NETWORK=public  # private requires Softlayer VPN
      - SOFTLAYER_CONTAINER
      - SOFTLAYER_PATH

      - BACKUP_LOCAL_PATHS
    links:
      - mysql
      - mongo

  latest:
    build:
      context: ./gamora
      args:
        - PIP_REPO_HOST_WITH_CREDS
        - PIP_REPO_USERNAME
        - PIP_REPO_PASSWORD
    image: bigdatauniversity/portal.gamora:latest
    command: "bash -c 'sleep 3600'"

  ##
  # MySQL
  ##
  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  ##
  # Mongo
  ##
  mongo:
    image: ${REGISTRY_HOST}portal.mongo:0.2.0-e.2
    environment:
      - "MONGO_ADMIN_USER=$MONGO_BACKUP_USER"
      - "MONGO_ADMIN_PASSWORD"
      - "FORUM_MONGO_USER=cs_comments_service"
      - "FORUM_MONGO_PASSWORD"
      - "FORUM_MONGO_DATABASE=cs_comments_service"
      - "EDXAPP_MONGO_USER=edxapp"
      - "EDXAPP_MONGO_PASSWORD"
      - "EDXAPP_MONGO_DB_NAME=edxapp"
