build:
  version: 2016-03-14 # version of the build schema.
  steps:
    builder:
      name: _env(IMAGE_NAME)
      dockerfile: Dockerfile
      secrets:
        pip:
          type: file
          value: _env(HOME)/.pip/pip.conf
