version: '2'
services:
  chell:
    build: ../app
    image: $REPO:$TAG
    environment:
      - DEBUG=chell:*
      - CHELL_ACCESS_KEY=access
      - CHELL_SECRET_KEY=secret

      - COMPANION_CUBE_URL=https://cc.example.com
      - COMPANION_CUBE_ACCESS_KEY=access
      - COMPANION_CUBE_SECRET_KEY=secret

      - MONGO_URI=mongodb://mongo/chell
    links:
      - mongo

  mongo:
    image: mongo:3.4
