version: '2'
services:
  chell:
    build: ../chell
    image: $REPO:$TAG
    environment:
      - DEBUG=chell:*
      - COOKIE_SECRET=secret

      - CHELL_ACCESS_KEY=access
      - CHELL_SECRET_KEY=secret

      - MESA_LMS_URL=https://mesa.example.com
      - MESA_OAUTH2_CLIENT_ID=client_id
      - MESA_OAUTH2_CLIENT_SECRET=client_secret
      - MESA_OAUTH2_CALLBACK_URL=https://chell.example.com/auth/mesa/callback

      - COMPANION_CUBE_URL=https://cc.example.com
      - COMPANION_CUBE_ACCESS_KEY=access
      - COMPANION_CUBE_SECRET_KEY=secret

      - MONGO_URI=mongodb://mongo/chell
    links:
      - mongo

  mongo:
    image: mongo:3.4
