version: '2'
services:
  chell:
    build: ../chell
    image: $REPO:$TAG
    environment:
      - DEBUG=chell:*
      - COOKIE_SECRET=secret

      - CHELL_ACCESS_KEY=access
      - CHELL_SECRET_KEY=secret

      - COURSE_DEV_LMS_URL=https://course-dev.example.com
      - COURSE_DEV_OAUTH2_CLIENT_ID=client_id
      - COURSE_DEV_OAUTH2_CLIENT_SECRET=client_secret
      - COURSE_DEV_OAUTH2_CALLBACK_URL=https://chell.example.com/auth/course-dev/callback

      - COMPANION_CUBE_URL=https://cc.example.com
      - COMPANION_CUBE_ACCESS_KEY=access
      - COMPANION_CUBE_SECRET_KEY=secret

      - MONGO_URI=mongodb://mongo/chell

      - S3_ENDPOINT
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET
    links:
      - mongo

  mongo:
    image: mongo:3.2
