version: '2'
services:
  heart:
    build: ../heart
    image: $REPO:$TAG
    environment:
      - DEBUG=heart:*
      - CHELL_ACCESS_KEY=access
      - CHELL_SECRET_KEY=secret

      - COMPANION_CUBE_URL=https://cc.example.com
      - COMPANION_CUBE_ACCESS_KEY=access
      - COMPANION_CUBE_SECRET_KEY=secret
