swagger: '2.0'
info:
  version: '0.1.0'
  title: Chell
  description: Chell's REST API
  termsOfService: ''
  contact:
    name: Partner Ecosystem Team, IBM Digital Business Group
    url: http://support.bigdatauniversity.com
    email: support@bigdatauniversity.com
  license:
    name: All rights reserved
host: chell.bigdatauniversity.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /courses:
    get:
      summary: List all courses.
      description: >-
        This API retrieve all courses that have been published at Big Data
        University.
      operationId: list_courses
      parameters:
        - $ref: '#/parameters/query_page'
        - $ref: '#/parameters/query_per_page'
      responses:
        200:
          description: Collection of course objects.
          schema:
            type: array
            items:
              $ref: '#/definitions/Course'
        401:
          description: Unauthorized.
          schema:
            $ref: '#/definitions/Error'
        422:
          description: Invalid parameters.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'

  /courses/{course_id}:
    get:
      summary: Retrieve an existing course.
      description: This API returns a single existing course object.
      operationId: retrieve_course
      parameters:
        - $ref: '#/parameters/path_course_id'
        - $ref: '#/parameters/header_format'
      responses:
        200:
          description: Course object.
          schema:
            $ref: '#/definitions/Course'
        401:
          description: Unauthorized.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Course not found.
          schema:
            $ref: '#/definitions/Error'
        422:
          description: Invalid parameters.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'

definitions:
  Course:
    description: Course object.
    type: object
    properties:
      id: # course-v1:<org>:<course>:<run>
        type: string
        description: Unique identifier for course.
      name:
        type: string
        description: Course name.
      organization:
        type: string
        description: Organization code.
      code:
        type: string
        description: Course code.
      short_description:
        type: string
        description: Short description.
      long_description:
        type: string
        description: Long description.
      created_at:
        type: string
        format: date-time
        description: Creation date-time.
      updated_at:
        type: string
        format: date-time
        description: Latest update date-time.
      versions:
        description: Colection of update objectss
        type: array
        items:
          description: Version object.
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for version.
            open_edx_id:
              type: string
              description: OpenEdx id for version.
            major:
              type: integer
              description: Version major.
            minor:
              type: integer
              description: Version minor.
            change_log:
              type: string
              description: Version change log.
            created_at:
              type: string
              format: date-time
              description: Creation date-time.
            updated_at:
              type: string
              format: date-time
              description: Latest update date-time.

  Error:
    description: Error details
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
        description: Error code
      message:
        type: string
        description: Error message
      description:
        type: string
        description: Error details

parameters:
  path_course_id:
    name: course_id
    in: path
    description: Unique identifier for course.
    required: true
    type: string

  header_format:
    name: Accept
    in: header
    description: >-
      Format for response object. Defaults to `application/json`.
    type: string
    required: false
    enum:
      - application/json
      - application/x-gzip

  query_page:
    name: page
    in: query
    description: Result page number.
    type: integer
    format: int32

  query_per_page:
    name: per_page
    in: query
    description: Number of results per page.
    type: integer
    format: int32
